FROM public.ecr.aws/p1t3u8a3/connectors/redshift:base

COPY . .
RUN apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc g++ musl-dev postgresql-dev && \
 python3 -m pip install -r deploy/requirements_redshift.txt --no-cache-dir && \
 apk --purge del .build-deps
ENV CLOUD_SERVICE=redshift \
    CONNECTION_STRING=postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}
ENTRYPOINT ./entrypoint.sh
