// Auto-generated by mobs/run.rb from mobs/mobile_messages.rb - do not edit.

import 'dart:typed_data';

import 'message.dart';
import 'writer.dart';

/// MobileMetadata (92)
class ORMobileMetadata extends ORMessage {
  ORMobileMetadata({
    required this.key,
    required this.value,
    int? timestamp,
  }) : super(92, timestamp);

  final String key;
  final String value;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(key);
    w.writeString(value);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileMetadata(92): timestamp:$timestamp key:$key value:$value';
}

/// MobileEvent (93)
class ORMobileEvent extends ORMessage {
  ORMobileEvent({
    required this.name,
    required this.payload,
    int? timestamp,
  }) : super(93, timestamp);

  final String name;
  final String payload;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(name);
    w.writeString(payload);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileEvent(93): timestamp:$timestamp name:$name payload:$payload';
}

/// MobileUserID (94)
class ORMobileUserID extends ORMessage {
  ORMobileUserID({
    required this.id,
    int? timestamp,
  }) : super(94, timestamp);

  final String id;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(id);
    return w.takeBytes();
  }

  @override
  String toString() => '-->> MobileUserID(94): timestamp:$timestamp id:$id';
}

/// MobileUserAnonymousID (95)
class ORMobileUserAnonymousID extends ORMessage {
  ORMobileUserAnonymousID({
    required this.id,
    int? timestamp,
  }) : super(95, timestamp);

  final String id;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(id);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileUserAnonymousID(95): timestamp:$timestamp id:$id';
}

/// MobileScreenChanges (96)
class ORMobileScreenChanges extends ORMessage {
  ORMobileScreenChanges({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    int? timestamp,
  }) : super(96, timestamp);

  final int x;
  final int y;
  final int width;
  final int height;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeUint(x);
    w.writeUint(y);
    w.writeUint(width);
    w.writeUint(height);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileScreenChanges(96): timestamp:$timestamp x:$x y:$y width:$width height:$height';
}

/// MobileCrash (97)
class ORMobileCrash extends ORMessage {
  ORMobileCrash({
    required this.name,
    required this.reason,
    required this.stacktrace,
    int? timestamp,
  }) : super(97, timestamp);

  final String name;
  final String reason;
  final String stacktrace;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(name);
    w.writeString(reason);
    w.writeString(stacktrace);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileCrash(97): timestamp:$timestamp name:$name reason:$reason stacktrace:$stacktrace';
}

/// MobileViewComponentEvent (98)
class ORMobileViewComponentEvent extends ORMessage {
  ORMobileViewComponentEvent({
    required this.screenName,
    required this.viewName,
    required this.visible,
    int? timestamp,
  }) : super(98, timestamp);

  final String screenName;
  final String viewName;
  final bool visible;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(screenName);
    w.writeString(viewName);
    w.writeBool(visible);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileViewComponentEvent(98): timestamp:$timestamp screenName:$screenName viewName:$viewName visible:$visible';
}

/// MobileClickEvent (100)
class ORMobileClickEvent extends ORMessage {
  ORMobileClickEvent({
    required this.label,
    required this.x,
    required this.y,
    int? timestamp,
  }) : super(100, timestamp);

  final String label;
  final int x;
  final int y;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(label);
    w.writeUint(x);
    w.writeUint(y);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileClickEvent(100): timestamp:$timestamp label:$label x:$x y:$y';
}

/// MobileInputEvent (101)
class ORMobileInputEvent extends ORMessage {
  ORMobileInputEvent({
    required this.value,
    required this.valueMasked,
    required this.label,
    int? timestamp,
  }) : super(101, timestamp);

  final String value;
  final bool valueMasked;
  final String label;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(value);
    w.writeBool(valueMasked);
    w.writeString(label);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileInputEvent(101): timestamp:$timestamp value:$value valueMasked:$valueMasked label:$label';
}

/// MobilePerformanceEvent (102)
class ORMobilePerformanceEvent extends ORMessage {
  ORMobilePerformanceEvent({
    required this.name,
    required this.value,
    int? timestamp,
  }) : super(102, timestamp);

  final String name;
  final int value;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(name);
    w.writeUint(value);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobilePerformanceEvent(102): timestamp:$timestamp name:$name value:$value';
}

/// MobileLog (103)
class ORMobileLog extends ORMessage {
  ORMobileLog({
    required this.severity,
    required this.content,
    int? timestamp,
  }) : super(103, timestamp);

  final String severity;
  final String content;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(severity);
    w.writeString(content);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileLog(103): timestamp:$timestamp severity:$severity content:$content';
}

/// MobileInternalError (104)
class ORMobileInternalError extends ORMessage {
  ORMobileInternalError({
    required this.content,
    int? timestamp,
  }) : super(104, timestamp);

  final String content;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(content);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileInternalError(104): timestamp:$timestamp content:$content';
}

/// MobileNetworkCall (105)
class ORMobileNetworkCall extends ORMessage {
  ORMobileNetworkCall({
    required this.type,
    required this.method,
    required this.url,
    required this.request,
    required this.response,
    required this.status,
    required this.duration,
    int? timestamp,
  }) : super(105, timestamp);

  final String type;
  final String method;
  final String url;
  final String request;
  final String response;
  final int status;
  final int duration;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(type);
    w.writeString(method);
    w.writeString(url);
    w.writeString(request);
    w.writeString(response);
    w.writeUint(status);
    w.writeUint(duration);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileNetworkCall(105): timestamp:$timestamp type:$type method:$method url:$url request:$request response:$response status:$status duration:$duration';
}

/// MobileSwipeEvent (106)
class ORMobileSwipeEvent extends ORMessage {
  ORMobileSwipeEvent({
    required this.label,
    required this.x,
    required this.y,
    required this.direction,
    int? timestamp,
  }) : super(106, timestamp);

  final String label;
  final int x;
  final int y;
  final String direction;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(label);
    w.writeUint(x);
    w.writeUint(y);
    w.writeString(direction);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileSwipeEvent(106): timestamp:$timestamp label:$label x:$x y:$y direction:$direction';
}

/// MobileBatchMeta (107)
class ORMobileBatchMeta extends ORMessage {
  ORMobileBatchMeta({
    required this.firstIndex,
    int? timestamp,
  }) : super(107, timestamp);

  final int firstIndex;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeUint(firstIndex);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileBatchMeta(107): timestamp:$timestamp firstIndex:$firstIndex';
}

/// MobileGraphQL (109)
class ORMobileGraphQL extends ORMessage {
  ORMobileGraphQL({
    required this.operationKind,
    required this.operationName,
    required this.variables,
    required this.response,
    required this.duration,
    int? timestamp,
  }) : super(109, timestamp);

  final String operationKind;
  final String operationName;
  final String variables;
  final String response;
  final int duration;

  @override
  Uint8List body() {
    final w = MessageWriter();
    w.writeString(operationKind);
    w.writeString(operationName);
    w.writeString(variables);
    w.writeString(response);
    w.writeUint(duration);
    return w.takeBytes();
  }

  @override
  String toString() =>
      '-->> MobileGraphQL(109): timestamp:$timestamp operationKind:$operationKind operationName:$operationName variables:$variables response:$response duration:$duration';
}
