SELECT throwIf((SELECT openreplay_migration_state()) != 5, 'Previous step is not done') AS check;

DROP TABLE IF EXISTS product_analytics.all_properties;
CREATE TABLE IF NOT EXISTS product_analytics.all_properties
(
    project_id        UInt16,
    property_name     String,
    is_event_property BOOL,
    auto_captured     BOOL,
    display_name      String                 DEFAULT '',
    description       String                 DEFAULT '',
    status            LowCardinality(String) DEFAULT 'visible' COMMENT 'visible/hidden/dropped',
    data_count        UInt32                 DEFAULT 1,
    query_count       UInt32                 DEFAULT 0,

    created_at        DateTime64,
    _edited_by_user   BOOL                   DEFAULT FALSE,
    _timestamp        DateTime               DEFAULT now()
) ENGINE = ReplacingMergeTree(_timestamp)
      ORDER BY (project_id, property_name, is_event_property, auto_captured);

CREATE OR REPLACE FUNCTION or_property_display_name AS(property_name)->multiIf(
        property_name == 'label', 'Label',
        property_name == 'hesitation_time', 'Hesitation Time',
        property_name == 'name', 'Name',
        property_name == 'payload', 'Payload',
        property_name == 'level', 'Level',
        property_name == 'source', 'Source',
        property_name == 'duration', 'Duration',
        property_name == 'context', 'Context',
        property_name == 'url_host', 'Hostname',
        property_name == 'url_path', 'Path',
        property_name == 'url_hostpath', 'URL Host and Path',
        property_name == 'request_start', 'Request Start',
        property_name == 'response_start', 'Response Start',
        property_name == 'response_end', 'Response End',
        property_name == 'dom_content_loaded_event_start', 'DOM Content Loaded Event Start',
        property_name == 'dom_content_loaded_event_end', 'DOM Content Loaded Event End',
        property_name == 'load_event_start', 'Load Event Start',
        property_name == 'load_event_end', 'Load Event End',
        property_name == 'first_paint', 'First Paint',
        property_name == 'first_contentful_paint_time', 'First Contentful-paint Time',
        property_name == 'speed_index', 'Speed Index',
        property_name == 'visually_complete', 'Visually Complete',
        property_name == 'time_to_interactive', 'Time To Interactive',
        property_name == 'ttfb', 'Time To First Byte',
        property_name == 'ttlb', 'Time To Last Byte',
        property_name == 'response_time', 'Response Time',
        property_name == 'dom_building_time', 'DOM Building Time',
        property_name == 'dom_content_loaded_event_time', 'DOM Content Loaded Event Time',
        property_name == 'load_event_time', 'Load Event Time',
        property_name == 'min_fps', 'Minimum Frame Rate',
        property_name == 'avg_fps', 'Average Frame Rate',
        property_name == 'max_fps', 'Maximum Frame Rate',
        property_name == 'min_cpu', 'Minimum CPU',
        property_name == 'avg_cpu', 'Average CPU',
        property_name == 'max_cpu', 'Maximum CPU',
        property_name == 'min_total_js_heap_size', 'Minimum Total JS Heap Size',
        property_name == 'avg_total_js_heap_size', 'Average Total JS Heap Size',
        property_name == 'max_total_js_heap_size', 'Maximum Total JS Heap Size',
        property_name == 'min_used_js_heap_size', 'Minimum Used JS Heap Size',
        property_name == 'avg_used_js_heap_size', 'Average Used JS Heap Size',
        property_name == 'max_used_js_heap_size', 'Maximum Used JS Heap Size',
        property_name == 'success', 'Success',
        property_name == 'request_body', 'Request Body',
        property_name == 'response_body', 'Response Body',
        property_name == 'transfer_size', 'Transfer Size',
        property_name == 'selector', 'CSS Selector',
        property_name == 'normalized_x', 'Normalized X',
        property_name == 'normalized_y', 'Normalized Y',
        property_name == 'message_id', 'Message ID',
        property_name == 'cls', 'Cumulative Layout Shift',
        property_name == 'lcp', 'Largest Contentful Paint',
        property_name == 'issue_type', 'Issue Type',
        property_name == 'url', 'URL',
        property_name == 'user_device', 'Device',
        property_name == 'user_device_type', 'Platform',
        property_name == 'message', 'Error Message',
        property_name == 'method', 'HTTP Method',
        property_name == 'status', 'Status Code',
        property_name == 'userState', 'State/Province',
        property_name == 'incident', 'Incident Reported By User',
        property_name == 'page_title', 'Page Title',
        '');

CREATE OR REPLACE FUNCTION or_property_visibility AS(property_name)->multiIf(
        property_name == 'label', 'visible',
        property_name == 'tag_id', 'hidden',
        property_name == 'inp', 'hidden',
        property_name == 'web_vitals', 'hidden',
        property_name = 'duration', 'visible',
        property_name = 'avg_cpu', 'hidden',
        property_name = 'avg_fps', 'hidden',
        property_name = 'avg_total_js_heap_size', 'hidden',
        property_name = 'avg_used_js_heap_size', 'hidden',
        property_name = 'dom_building_time', 'hidden',
        property_name = 'dom_content_loaded_event_end', 'hidden',
        property_name = 'dom_content_loaded_event_start', 'hidden',
        property_name = 'dom_content_loaded_event_time', 'hidden',
        property_name = 'first_paint', 'hidden',
        property_name = 'load_event_end', 'hidden',
        property_name = 'load_event_start', 'hidden',
        property_name = 'load_event_time', 'hidden',
        property_name = 'url_hostpath', 'hidden',
        property_name = 'visually_complete', 'hidden',
        property_name = 'time_to_interactive', 'hidden',
        property_name = 'ttlb', 'hidden',
        property_name = 'transfer_size', 'hidden',
        property_name = 'source', 'hidden',
        property_name = 'request_start', 'hidden',
        property_name = 'response_end', 'hidden',
        property_name = 'response_start', 'hidden',
        property_name = 'response_time', 'hidden',
        property_name = 'normalized_x', 'visible',
        property_name = 'normalized_y', 'visible',
        property_name = 'max_total_js_heap_size', 'hidden',
        property_name = 'min_total_js_heap_size', 'hidden',
        property_name = 'userAnonymousId', 'hidden',
        property_name = 'user_device', 'hidden',
        'visible');


CREATE MATERIALIZED VIEW IF NOT EXISTS product_analytics.all_properties_extractor_mv
    TO product_analytics.all_properties AS
SELECT project_id,
       property_name,
       TRUE                                    AS is_event_property,
       auto_captured_property                  AS auto_captured,
--        Think about display name if autocaptured and not autocaptured
       or_property_display_name(property_name) AS display_name,
       ''                                      AS description,
       or_property_visibility(property_name)   AS status,
       0                                       AS data_count,
       0                                       AS query_count,
       event_properties.created_at             AS created_at,
       FALSE                                   AS _edited_by_user
FROM product_analytics.event_properties;
-- -------- END ---------
CREATE OR REPLACE FUNCTION openreplay_migration_state AS() -> 6;
