FROM python:3.13-alpine
LABEL Maintainer="Rajesh Rajendran<rjshrjndrn@gmail.com>"
LABEL Maintainer="KRAIEM Taha Yassine<tahayk2@gmail.com>"
RUN apk add --no-cache build-base tini
ARG envarg
ENV APP_NAME=crons \
    PG_MINCONN=2 \
    PG_MAXCONN=10 \
    PRIVATE_ENDPOINTS=true \
    ENTERPRISE_BUILD=${envarg} \
    ACTION="" \
    PG_POOL=false

WORKDIR /work
COPY requirements-crons.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade uv