# ignore .git and .cache folders
.git
.cache
**/build.sh
**/build_*.sh
**/*deploy.sh
Dockerfile*

app.py
app_crons.py
requirements.txt
requirements-crons.txt
build.sh
build_crons.sh
entrypoint.sh
entrypoint_crons.sh