#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# cd tracker/tracker
# pwd
# npm run lint-front
# echo "Linted root:"
# pwd

git diff @{push} --cached --name-only | grep
if git diff @{push} --cached --name-only | grep --quiet 'tracker$'
then
  pwd
else
  echo "skipping other dir"
  exit 0
fi
