/*
 * Legacy palette names, kept so the remaining legacy utility classes (`text-gray-dark`,
 * `bg-active-blue`, …) and `$vars` in CSS modules still resolve. Every name points at a
 * kit token, so they follow the kit's light/dark themes; prefer the tokens directly.
 */
const t = (name) => `var(--m-${name})`;
const glass = `color-mix(in srgb, ${t('surface-default')} 50%, transparent)`;

module.exports = {
  main: t('content-accent'),
  'gray-light-shade': t('border-subtle'),
  'gray-lightest': t('surface-sunken'),
  'gray-lighter': t('surface-hover'),
  'gray-light': t('border-default'),
  'gray-bg': t('border-strong'),
  'gray-medium': t('content-muted'),
  'gray-dark': t('content-secondary'),
  'gray-darkest': t('content-primary'),
  'gray-light-blue': t('surface-sunken'),
  teal: t('content-accent'),
  'teal-dark': t('content-accent'),
  'teal-light': t('surface-selected'),
  tealx: t('content-accent'),
  'tealx-light': t('surface-selected'),
  'tealx-light-border': t('border-accent'),
  'tealx-lightest': t('surface-selected'),
  orange: t('content-warning'),
  yellow: t('status-warning-bg'),
  yellow2: t('content-warning'),
  'orange-dark': t('content-warning'),
  green: t('content-success'),
  green2: t('content-success'),
  'green-light': t('status-success-bg'),
  'green-dark': t('content-success'),
  red: t('content-danger'),
  red2: t('content-warning'),
  'red-light': t('status-danger-bg'),
  'red-lightest': t('status-danger-bg'),
  blue: t('content-accent'),
  blue2: t('content-accent'),
  'active-blue': t('surface-selected'),
  'active-dark-blue': t('surface-active'),
  'bg-blue': t('surface-selected'),
  'active-blue-border': t('border-accent'),
  pink: t('status-danger-bg'),
  'light-blue-bg': t('surface-selected'),
  white: t('surface-default'),
  black: t('content-primary'),
  'gray-border': t('border-strong'),
  borderColor: {
    default: t('border-default'),
    'gray-light-shade': t('border-subtle'),
    primary: t('border-accent'),
    transparent: 'transparent',
  },
  transparent: 'transparent',
  cyan: t('surface-selected'),
  amber: t('status-warning-bg'),
  'amber-medium': t('status-warning-border'),
  glassWhite: glass,
  glassMint: glass,
  glassLavander: glass,
  blueLight: t('surface-selected'),
  offWhite: t('surface-sunken'),
  'disabled-text': t('content-disabled'),
  'indigo-lightest': t('surface-selected'),
  indigo: t('content-accent'),
  'warning-surface': t('status-warning-bg'),
  'warning-text': t('content-warning'),
  'control-selected-bg': t('surface-default'),
  'tag-brand-bg': t('surface-selected'),

  /** DEPRECATED */
  figmaColors: {
    'accent-secondary': t('content-accent'),
    main: t('content-accent'),
    'primary-outlined-hover-background': t('surface-hover'),
    'primary-outlined-resting-border': t('border-accent'),
    'secondary-outlined-hover-background': t('surface-hover'),
    'secondary-outlined-resting-border': t('border-accent'),
    'text-disabled': t('content-disabled'),
    'text-primary': t('content-primary'),
    'outlined-border': t('border-default'),
    divider: t('border-subtle'),
  },
};
