#!/bin/sh

#
# tl;dr: use or create a virtual environment.
#
# If there is no directory called .venv, create a virtual
# environment called .venv, install dependencies from requirements.txt
# and spawn a new shell inside that venv. The Python version used to
# create the venv can be passed as first argument.
#
# Otherwise spawn a new shell for the virtualenv .venv, possibly run
# the provided command: ./venv ipython
#
# TODO: investigate https://github.com/berdario/pew
#

set -xe

PYTHON=$1
VENV="$HOME/.cache/venv-$(basename $(pwd))-$(echo -n $(pwd) | md5sum | cut -d ' ' -f1)"

if [ "$PYTHON" = "" ]; then
    PYTHON="python3"
fi;

if test -d $VENV; then
    if [[ -z "$MYVENV" ]]; then
        export MYVENV=1
        source $VENV/bin/activate
        if [[ -z "$@" ]]; then
            if test -f $VENV/bin/rc.sh; then
                bash --rcfile $VENV/bin/rc.sh
            else
                bash --norc --noprofile
            fi
        else
            exec "$@"
        fi
    else
        echo "You are already in a virtual environment!"
    fi
else
    $PYTHON -m venv --upgrade-deps --prompt="$(basename $(pwd)) :" $VENV
    curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    ./venv python get-pip.py
    rm -r get-pip.py
    echo VENV_PATH=$(pwd) > $VENV/bin/rc.sh
    cat $VENV/bin/activate >> $VENV/bin/rc.sh
    ./venv "$@"
fi
