const fs = require('fs');
const colors = require('../app/theme/colors.js');

const flattenColors = (colors) => {
  let flatColors = {};
  for (const [key, value] of Object.entries(colors)) {
    if (typeof value === 'object' && value !== null && key !== 'dark') {
      for (const [nestedKey, nestedValue] of Object.entries(value)) {
        flatColors[`${key}-${nestedKey}`] = `${key}-${nestedKey}`;
      }
    } else if (key !== 'dark') {
      flatColors[key] = key;
    }
  }
  return flatColors;
};

const flatColors = flattenColors(colors);

// Only `fill-*`: the legacy Icon builds `fill-${color}` at runtime, so Tailwind's
// scanner can't see those. Every other legacy palette class comes from Tailwind
// (tailwind.config.js colors), which only emits what the sources use.
const generatedCSS = `/* Auto-generated by scripts/colors.js, DO NOT EDIT */
/* Uses CSS variables (--color-*) generated by Tailwind config */

${Object.entries(flatColors).map(([name, key]) => `.fill-${name.replace(/ /g, '-')} { fill: var(--color-${key.replace(/ /g, '-')}) }`).join('\n')}
`;

// Write the generated CSS to a file
fs.writeFileSync('app/styles/colors-autogen.css', generatedCSS);
