#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# cd tracker/tracker-assist
# pwd
# npm run lint-front
# echo "Linted root:"
# pwd


if git diff @{push} --cached --name-only | grep --quiet 'tracker$'
then
  pwd
else
  exit 0
fi
