#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# cd tracker/tracker-assist
# pwd
# npm run lint-front
# echo "Linted root:"
# pwd


if git diff --cached --name-only | grep --quiet 'tracker-assist$'
then
  pwd
else
  echo "skipping other dir"
  exit 0
fi
