#!/usr/bin/env sh
#. "$(dirname -- "$0")/_/husky.sh"

git diff --cached --name-only | grep 'tracker$'

if git diff --cached --name-only | grep --quiet '^tracker/tracker/'
then
  pwd
  echo "tracker"
fi

if git diff --cached --name-only | grep --quiet '^tracker/tracker-assist/'
then
  pwd
  echo "tracker-assist"
fi

echo "end"
