import { Environment, RunData, TestCase } from './types';

const HOUR = 3600000;
const NOW = Date.now();
const ago = (hours: number) => NOW - hours * HOUR;

const EVERY_DAY = { days: [0, 1, 2, 3, 4, 5, 6], time: '06:00' };
const WEEKDAYS = { days: [1, 2, 3, 4, 5], time: '09:00' };
const MWF = { days: [1, 3, 5], time: '17:00' };

export const MOCK_ENVIRONMENTS: Environment[] = [
  {
    id: 'env-prod',
    name: 'Production',
    url: 'https://app.example.com',
    username: 'bot@example.com',
    password: 'prod-secret',
  },
  {
    id: 'env-staging',
    name: 'Staging',
    url: 'https://staging.example.com',
    username: 'qa@example.com',
    password: 'staging-secret',
    ignoreHttpsErrors: true,
    headers: [{ name: 'X-Env', value: 'staging' }],
  },
  {
    id: 'env-qa',
    name: 'QA',
    url: 'https://qa.example.com',
  },
];

// Drafts: surfaced by the agent only once it has gathered enough sessions to be
// confident the journey is complete. Active/paused tests are already approved.
export const MOCK_TEST_CASES: TestCase[] = [
  // ---- drafts ----------------------------------------------------------
  {
    key: 'tc-signup',
    title: 'New sign-up flow',
    status: 'draft',
    isNew: true,
    tags: ['Onboarding'],
    envName: 'Production',
    resolution: 'desktop',
    region: 'paris',
    steps: [
      'Open the sign-up page',
      'Enter email and password',
      'Accept terms',
      'Click create account',
      'Land on the onboarding screen',
    ],
    alternatives: [
      { afterStep: 2, note: 'Skip terms · seen in 12% of sessions' },
    ],
  },
  {
    key: 'tc-byoc',
    title: 'BYOC setup flow',
    status: 'draft',
    isNew: true,
    tags: ['Onboarding'],
    steps: [
      'Open the deployment settings',
      'Choose bring-your-own-cloud',
      'Connect the cloud account',
      'Pick a region',
      'Confirm and deploy',
    ],
  },
  {
    key: 'tc-reset',
    title: 'Password reset',
    status: 'draft',
    tags: ['Auth'],
    envName: 'QA',
    steps: [
      'Open the login page',
      'Click forgot password',
      'Enter the account email',
      'Open the reset link',
      'Set a new password',
      'Sign in with the new password',
    ],
  },
  {
    key: 'tc-coupon',
    title: 'Apply coupon at checkout',
    status: 'draft',
    isNew: true,
    tags: ['Checkout'],
    steps: [
      'Add an item to the cart',
      'Go to checkout',
      'Enter a coupon code',
      'Verify the discount is applied',
    ],
  },
  {
    key: 'tc-invite',
    title: 'Add a team member',
    status: 'draft',
    tags: ['Settings'],
    envName: 'QA',
    steps: [
      'Open team settings',
      'Click invite member',
      'Enter an email address',
      'Pick a role',
      'Send the invite',
    ],
  },

  // ---- approved tests --------------------------------------------------
  {
    key: 'tc-checkout',
    title: 'Checkout flow',
    status: 'active',
    tags: ['Checkout'],
    envName: 'Production',
    schedule: { days: [0, 1, 2, 3, 4, 5, 6], time: '06:00' },
    lastResult: 'passed',
    lastRunAt: ago(2),
    recent: ['passed', 'passed', 'failed', 'passed', 'passed'],
    steps: [
      'Add a sample product to the cart',
      'Navigate to the cart',
      'Proceed to checkout',
      'Submit the order',
      'Verify the order confirmation page',
    ],
  },
  {
    key: 'tc-login',
    title: 'Login flow',
    status: 'active',
    tags: ['Auth'],
    envName: 'QA',
    schedule: WEEKDAYS,
    resolution: 'mobile',
    region: 'ny',
    lastResult: 'failed',
    lastRunAt: ago(5),
    recent: ['passed', 'passed', 'passed', 'failed', 'failed'],
    steps: [
      'Navigate to the login page',
      'Enter the provided credentials',
      'Click the submit button',
      'Verify redirect to dashboard',
    ],
  },
  {
    key: 'tc-search',
    title: 'Search & filter',
    status: 'active',
    tags: ['Search'],
    envName: 'Production',
    schedule: WEEKDAYS,
    lastResult: 'passed',
    lastRunAt: ago(9),
    recent: ['passed', 'passed', 'passed', 'passed', 'passed'],
    steps: [
      'Open the main search bar',
      'Type a product keyword',
      'Select a suggestion',
      'Apply a price filter',
    ],
  },
  {
    key: 'tc-billing',
    title: 'Update billing card',
    status: 'active',
    tags: ['Billing'],
    envName: 'Staging',
    schedule: MWF,
    lastResult: 'failed',
    lastRunAt: ago(11),
    recent: ['passed', 'failed', 'failed', 'failed', 'failed'],
    steps: [
      'Open billing settings',
      'Click update card',
      'Enter new card details',
      'Save and verify confirmation',
    ],
  },
  {
    key: 'tc-create-project',
    title: 'Create project',
    status: 'active',
    tags: ['Projects'],
    envName: 'Production',
    schedule: EVERY_DAY,
    lastResult: 'passed',
    lastRunAt: ago(3),
    recent: ['passed', 'passed', 'passed', 'passed', 'passed'],
    steps: [
      'Click new project',
      'Enter a project name',
      'Pick a template',
      'Create the project',
    ],
  },
  {
    key: 'tc-invite-active',
    title: 'Invite teammate',
    status: 'active',
    tags: ['Settings'],
    envName: 'QA',
    schedule: WEEKDAYS,
    lastResult: 'passed',
    lastRunAt: ago(14),
    recent: ['failed', 'passed', 'passed', 'passed', 'passed'],
    steps: [
      'Open team settings',
      'Send an invite',
      'Verify the pending invite appears',
    ],
  },
  {
    key: 'tc-2fa',
    title: 'Enable two-factor auth',
    status: 'active',
    tags: ['Auth'],
    envName: 'QA',
    schedule: WEEKDAYS,
    lastResult: 'passed',
    lastRunAt: ago(20),
    recent: ['passed', 'passed', 'passed', 'passed', 'passed'],
    steps: [
      'Open security settings',
      'Start 2FA setup',
      'Scan the QR code',
      'Confirm with a code',
    ],
  },
  {
    key: 'tc-invoice',
    title: 'Download invoice',
    status: 'active',
    tags: ['Billing'],
    envName: 'Production',
    schedule: { days: [1], time: '08:00' },
    lastResult: 'passed',
    lastRunAt: ago(26),
    recent: ['passed', 'passed', 'passed', 'passed', 'passed'],
    steps: ['Open billing history', 'Pick an invoice', 'Download the PDF'],
  },
  {
    key: 'tc-profile',
    title: 'Upload profile photo',
    status: 'active',
    tags: ['Profile'],
    envName: 'Staging',
    schedule: WEEKDAYS,
    lastResult: 'passed',
    lastRunAt: ago(30),
    recent: ['passed', 'failed', 'passed', 'passed', 'passed'],
    steps: [
      'Open profile settings',
      'Click change photo',
      'Upload an image',
      'Save and verify it shows',
    ],
  },

  // ---- paused ----------------------------------------------------------
  {
    key: 'tc-onboarding-tour',
    title: 'Onboarding tour',
    status: 'paused',
    tags: ['Onboarding'],
    envName: 'Staging',
    schedule: null,
    lastResult: 'passed',
    lastRunAt: ago(72),
    recent: ['passed', 'passed', 'passed', 'passed', 'passed'],
    steps: [
      'Start the product tour',
      'Step through each tooltip',
      'Finish and verify completion',
    ],
  },
  {
    key: 'tc-bulk-export',
    title: 'Bulk data export',
    status: 'paused',
    tags: ['Settings'],
    envName: 'QA',
    schedule: null,
    lastResult: 'failed',
    lastRunAt: ago(96),
    recent: ['failed', 'failed', 'passed', 'passed', 'passed'],
    steps: [
      'Open data settings',
      'Request a full export',
      'Wait for the export to finish',
      'Download the archive',
    ],
  },
];

// A run is one execution of a test. The same test shows up every time it runs, with
// its own timestamp — that's what makes this a log, not a second list of tests.
export const MOCK_RUNS: RunData[] = [
  // ---- in progress (today) --------------------------------------------
  {
    key: 'r1',
    testName: 'Checkout flow',
    date: ago(0.05),
    status: 'running',
    envName: 'Production',
    resolution: 'desktop',
    region: 'paris',
    tags: ['Checkout'],
    steps: [
      { step: 'Add a sample product to the cart', status: 'passed' },
      { step: 'Navigate to the cart', status: 'passed' },
      { step: 'Proceed to checkout', status: 'running' },
      { step: 'Submit the order', status: 'pending' },
      { step: 'Verify the order confirmation page', status: 'pending' },
    ],
  },
  // ---- today -----------------------------------------------------------
  {
    key: 'r2',
    testName: 'Login flow',
    date: ago(2),
    duration: 5430,
    status: 'failed',
    failedStep: 2,
    envName: 'QA',
    resolution: 'mobile',
    region: 'ny',
    tags: ['Auth'],
    error:
      'Submit button not found — timed out after 5s waiting for [type="submit"].',
    steps: [
      { step: 'Navigate to the login page', status: 'passed' },
      { step: 'Enter the provided credentials', status: 'passed' },
      { step: 'Click the submit button', status: 'failed' },
      { step: 'Verify redirect to dashboard', status: 'skipped' },
    ],
  },
  {
    key: 'r3',
    testName: 'Checkout flow',
    date: ago(4),
    duration: 2100,
    status: 'passed',
    envName: 'Production',
    tags: ['Checkout'],
    steps: [
      { step: 'Add a sample product to the cart', status: 'passed' },
      { step: 'Navigate to the cart', status: 'passed' },
      { step: 'Proceed to checkout', status: 'passed' },
      { step: 'Submit the order', status: 'passed' },
      { step: 'Verify the order confirmation page', status: 'passed' },
    ],
  },
  {
    key: 'r4',
    testName: 'Search & filter',
    date: ago(7),
    duration: 1800,
    status: 'passed',
    envName: 'Production',
    tags: ['Search'],
    steps: [
      { step: 'Open the main search bar', status: 'passed' },
      { step: 'Type a product keyword', status: 'passed' },
      { step: 'Select a suggestion', status: 'passed' },
      { step: 'Apply a price filter', status: 'passed' },
    ],
  },
  // ---- yesterday -------------------------------------------------------
  {
    key: 'r5',
    testName: 'Update billing card',
    date: ago(28),
    duration: 4200,
    status: 'failed',
    failedStep: 2,
    envName: 'Staging',
    resolution: 'tablet',
    region: 'sao-paulo',
    tags: ['Billing'],
    error: 'Card field rejected input — Stripe iframe did not load in time.',
    steps: [
      { step: 'Open billing settings', status: 'passed' },
      { step: 'Click update card', status: 'passed' },
      { step: 'Enter new card details', status: 'failed' },
      { step: 'Save and verify confirmation', status: 'skipped' },
    ],
  },
  {
    key: 'r6',
    testName: 'Checkout flow',
    date: ago(30),
    duration: 2400,
    status: 'passed',
    envName: 'Production',
    tags: ['Checkout'],
    steps: [
      { step: 'Add a sample product to the cart', status: 'passed' },
      { step: 'Navigate to the cart', status: 'passed' },
      { step: 'Proceed to checkout', status: 'passed' },
      { step: 'Submit the order', status: 'passed' },
      { step: 'Verify the order confirmation page', status: 'passed' },
    ],
  },
  {
    key: 'r7',
    testName: 'Login flow',
    date: ago(31),
    duration: 1900,
    status: 'passed',
    envName: 'QA',
    tags: ['Auth'],
    steps: [
      { step: 'Navigate to the login page', status: 'passed' },
      { step: 'Enter the provided credentials', status: 'passed' },
      { step: 'Click the submit button', status: 'passed' },
      { step: 'Verify redirect to dashboard', status: 'passed' },
    ],
  },
  // ---- earlier ---------------------------------------------------------
  {
    key: 'r8',
    testName: 'Create project',
    date: ago(50),
    duration: 2600,
    status: 'passed',
    envName: 'Production',
    tags: ['Projects'],
    steps: [
      { step: 'Click new project', status: 'passed' },
      { step: 'Enter a project name', status: 'passed' },
      { step: 'Pick a template', status: 'passed' },
      { step: 'Create the project', status: 'passed' },
    ],
  },
  {
    key: 'r9',
    testName: 'Checkout flow',
    date: ago(54),
    duration: 2200,
    status: 'passed',
    envName: 'Production',
    tags: ['Checkout'],
    steps: [
      { step: 'Add a sample product to the cart', status: 'passed' },
      { step: 'Navigate to the cart', status: 'passed' },
      { step: 'Proceed to checkout', status: 'passed' },
      { step: 'Submit the order', status: 'passed' },
      { step: 'Verify the order confirmation page', status: 'passed' },
    ],
  },
];
