CREATE TABLE IF NOT EXISTS connector_events
(
    sessionid                          BIGINT,
    consolelog_level                   VARCHAR(5000),
    consolelog_value                   VARCHAR(5000),
    customevent_name                   VARCHAR(5000),
    customevent_payload                VARCHAR(5000),
    jsexception_message                VARCHAR(5000),
    jsexception_name                   VARCHAR(5000),
    jsexception_payload                VARCHAR(5000),
    jsexception_metadata               VARCHAR(5000),
    networkrequest_type                VARCHAR(5000),
    networkrequest_method              VARCHAR(5000),
    networkrequest_url                 VARCHAR(5000),
    networkrequest_request             VARCHAR(5000),
    networkrequest_response            VARCHAR(5000),
    networkrequest_status              BIGINT,
    networkrequest_timestamp           BIGINT,
    networkrequest_duration            BIGINT,
    issueevent_message_id              BIGINT,
    issueevent_timestamp               BIGINT,
    issueevent_type                    VARCHAR(5000),
    issueevent_context_string          VARCHAR(5000),
    issueevent_context                 VARCHAR(5000),
    issueevent_payload                 VARCHAR(5000),
    issueevent_url                     VARCHAR(5000),
    customissue_name                   VARCHAR(5000),
    customissue_payload                VARCHAR(5000),
    received_at                        BIGINT,
    batch_order_number                 BIGINT
);
