CREATE TABLE IF NOT EXISTS connector_events
(
    sessionid                          BIGINT,
    consolelog_level                   VARCHAR(8000),
    consolelog_value                   VARCHAR(8000),
    clickevent_hesitationtime			BIGINT,
    clickevent_messageid			BIGINT,
    clickevent_label			VARCHAR(8000),
    clickevent_selector			VARCHAR(8000),
    customevent_name                   VARCHAR(8000),
    customevent_payload                VARCHAR(8000),
    jsexception_message                VARCHAR(8000),
    jsexception_name                   VARCHAR(8000),
    jsexception_payload                VARCHAR(8000),
    jsexception_metadata               VARCHAR(8000),
    networkrequest_type                VARCHAR(8000),
    networkrequest_method              VARCHAR(8000),
    networkrequest_url                 VARCHAR(8000),
    networkrequest_request             VARCHAR(8000),
    networkrequest_response            VARCHAR(8000),
    networkrequest_status              BIGINT,
    networkrequest_timestamp           BIGINT,
    networkrequest_duration            BIGINT,
    issueevent_message_id              BIGINT,
    issueevent_timestamp               BIGINT,
    issueevent_type                    VARCHAR(8000),
    issueevent_context_string          VARCHAR(8000),
    issueevent_context                 VARCHAR(8000),
    issueevent_payload                 VARCHAR(8000),
    issueevent_url                     VARCHAR(8000),
    customissue_name                   VARCHAR(8000),
    customissue_payload                VARCHAR(8000),
    received_at                        BIGINT,
    batch_order_number                 BIGINT
);
