{
 "title": "Openreplay Components Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time", "label": "Data sampling time", "query": "1m,2m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "Requests total / ${time}",
   "type": "stat",
   "description": "Number of all requests that have been processed / service",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(requests_total[${time}]))"
    }
   ]
  },
  {
   "title": "Messages processed / ${time}",
   "type": "stat",
   "description": "Number of all messages that have been processed / service",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(messages_total[${time}]))"
    }
   ]
  },
  {
   "title": "Messages saved / ${time}",
   "type": "stat",
   "description": "Number of messages that have been saved to session files",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(messages_saved[${time}]))"
    }
   ]
  },
  {
   "title": "Sessions stored in s3 / ${time}",
   "type": "stat",
   "description": "Number of all sessions that have been compressed and saved to s3",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sessions_total{container=\"storage\"}[${time}]))"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Session size histogram / ${time}",
   "type": "heatmap",
   "description": "Sizes of saved sessions (before compression)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(sessions_size_sum[${time}]))/sum(rate(sessions_size_count[${time}]))"
    }
   ]
  },
  {
   "title": "Archiving duration histogram / ${time}",
   "type": "heatmap",
   "description": "Durations of archiving process for all handled sessions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(archiving_duration_sum[${time}]))/sum(rate(archiving_duration_count[${time}]))"
    }
   ]
  },
  {
   "title": "Sink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Message size histogram / ${time}",
   "type": "heatmap",
   "description": "Sizes of saved messages\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(messages_size_sum[${time}])) / sum(rate(messages_size_count[${time}]))"
    }
   ]
  },
  {
   "title": "Http",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request body size / ${time}",
   "type": "heatmap",
   "description": "Sizes of request’s body for start and ingest endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(requests_body_size_sum[${time}]))/sum(rate(requests_body_size_count[${time}]))"
    }
   ]
  },
  {
   "title": "Request duration / ${time}",
   "type": "heatmap",
   "description": "Request processing duration for all endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(requests_duration_sum[${time}]))/sum(rate(requests_duration_count[${time}]))"
    }
   ]
  },
  {
   "title": "ender",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "description": "Number of active sessions (unfinished sessions)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(sessions_active)", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "Sessions processed / ${time}",
   "type": "graph",
   "description": "Number of all sessions that have been processed / service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(sessions_total{container=\"ender\"}[${time}]))"
    }
   ]
  },
  {
   "title": "Assets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Assets processed / ${time}",
   "type": "graph",
   "description": "Number of all assets that have been processed / service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(assets_total[${time}]))"
    }
   ]
  },
  {
   "title": "Assets downloaded / ${time}",
   "type": "graph",
   "description": "Number of all assets that have been downloaded / service",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(assets_downloaded[${time}]))"
    }
   ]
  },
  {
   "title": "Db",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Batch size / ${time}",
   "type": "heatmap",
   "description": "Size of batch in bytes before execution in PG",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(batch_size_bytes_sum[${time}]))/sum(rate(batch_size_bytes_count[${time}]))"
    }
   ]
  },
  {
   "title": "Number of sql requests before PG execution / ${time}",
   "type": "heatmap",
   "description": "Number of sql requests before execution in PG",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(batch_size_lines_sum[${time}]))/sum(rate(batch_size_lines_count[${time}]))"
    },
    {
     "expr": "sum(rate(batch_size_lines_sum[${time}]))/sum(rate(batch_size_lines_count[${time}]))"
    }
   ]
  },
  {
   "title": "Duration of sql request / ${time}",
   "type": "heatmap",
   "description": "Duration of SQL request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by (le) (rate(sql_request_time_bucket[${time}]))"
    }
   ]
  }
 ]
}