# coding: utf-8
from sqlalchemy import BigInteger, Boolean, Column, Integer, ARRAY, VARCHAR, text, VARCHAR
from sqlalchemy.ext.declarative import declarative_base
from pathlib import Path
from decouple import config

DATABASE = config('DATABASE_NAME')

Base = declarative_base()
metadata = Base.metadata

base_path = Path(__file__).parent.parent

# Get a table name from a configuration file
try:
    events_table_name = config('events_table_name', default='connector_events')
except KeyError as e:
    events_table_name = None
    print(repr(e))
try:
    events_detailed_table_name = config('events_detailed_table_name', default='connector_events_detailed')
except KeyError as e:
    print(repr(e))
    events_detailed_table_name = None
sessions_table_name = config('sessions_table', default='connector_user_sessions')


class Session(Base):
    __tablename__ = sessions_table_name

    sessionid = Column(BigInteger, primary_key=True)
    user_agent = Column(VARCHAR(5000))
    user_browser = Column(VARCHAR(5000))
    user_browser_version = Column(VARCHAR(5000))
    user_country = Column(VARCHAR(5000))
    user_device = Column(VARCHAR(5000))
    user_device_heap_size = Column(BigInteger)
    user_device_memory_size = Column(BigInteger)
    user_device_type = Column(VARCHAR(5000))
    user_os = Column(VARCHAR(5000))
    user_os_version = Column(VARCHAR(5000))
    user_uuid = Column(VARCHAR(5000))
    connection_effective_bandwidth = Column(BigInteger)  # Downlink
    connection_type = Column(VARCHAR(5000))  # "bluetooth", "cellular", "ethernet", "none", "wifi", "wimax", "other", "unknown"
    metadata_key = Column(VARCHAR(5000))
    metadata_value = Column(VARCHAR(5000))
    referrer = Column(VARCHAR(5000))
    user_anonymous_id = Column(VARCHAR(5000))
    user_id = Column(VARCHAR(5000))

    # TIME
    session_start_timestamp = Column(BigInteger)
    session_end_timestamp = Column(BigInteger)
    session_duration = Column(BigInteger)

    # SPEED INDEX RELATED
    first_contentful_paint = Column(BigInteger)
    speed_index = Column(BigInteger)
    visually_complete = Column(BigInteger)
    timing_time_to_interactive = Column(BigInteger)

    # PERFORMANCE
    avg_cpu = Column(Integer)
    avg_fps = Column(BigInteger)
    max_cpu = Column(Integer)
    max_fps = Column(BigInteger)
    max_total_js_heap_size = Column(BigInteger)
    max_used_js_heap_size = Column(BigInteger)

    # ISSUES AND EVENTS
    js_exceptions_count = Column(BigInteger)
    long_tasks_total_duration = Column(BigInteger)
    long_tasks_max_duration = Column(BigInteger)
    long_tasks_count = Column(BigInteger)
    inputs_count = Column(BigInteger)
    clicks_count = Column(BigInteger)
    issues_count = Column(BigInteger)
    issues = ARRAY(VARCHAR(5000))
    urls_count = Column(BigInteger)
    urls = ARRAY(VARCHAR(5000))


class Event(Base):
    __tablename__ = events_table_name

    sessionid = Column(BigInteger, primary_key=True)
    connectioninformation_downlink = Column(BigInteger)
    connectioninformation_type = Column(VARCHAR(5000))
    consolelog_level = Column(VARCHAR(5000))
    consolelog_value = Column(VARCHAR(5000))
    customevent_name = Column(VARCHAR(5000))
    customevent_payload = Column(VARCHAR(5000))
    jsexception_message = Column(VARCHAR(5000))
    jsexception_name = Column(VARCHAR(5000))
    jsexception_payload = Column(VARCHAR(5000))
    jsexception_metadata = Column(VARCHAR(5000))
    metadata_key = Column(VARCHAR(5000))
    metadata_value = Column(VARCHAR(5000))
    networkrequest_type = Column(VARCHAR(5000))
    networkrequest_method = Column(VARCHAR(5000))
    networkrequest_url = Column(VARCHAR(5000))
    networkrequest_request = Column(VARCHAR(5000))
    networkrequest_response = Column(VARCHAR(5000))
    networkrequest_status = Column(BigInteger)
    networkrequest_timestamp = Column(BigInteger)
    networkrequest_duration = Column(BigInteger)
    mouseclick_id = Column(BigInteger)
    mouseclick_hesitationtime = Column(BigInteger)
    mouseclick_label = Column(VARCHAR(5000))
    pageevent_firstcontentfulpaint = Column(BigInteger)
    pageevent_firstpaint = Column(BigInteger)
    pageevent_messageid = Column(BigInteger)
    pageevent_referrer = Column(VARCHAR(5000))
    pageevent_speedindex = Column(BigInteger)
    pageevent_timestamp = Column(BigInteger)
    pageevent_url = Column(VARCHAR(5000))
    pagerendertiming_timetointeractive = Column(BigInteger)
    pagerendertiming_visuallycomplete = Column(BigInteger)
    integrationevent_timestamp = Column(BigInteger)
    integrationevent_source = Column(VARCHAR(5000))
    integrationevent_name = Column(VARCHAR(5000))
    integrationevent_message = Column(VARCHAR(5000))
    integrationevent_payload = Column(VARCHAR(5000))
    setviewportsize_height = Column(BigInteger)
    setviewportsize_width = Column(BigInteger)
    timestamp_timestamp = Column(BigInteger)
    user_anonymous_id = Column(VARCHAR(5000))
    user_id = Column(VARCHAR(5000))
    issueevent_message_id = Column(BigInteger)
    issueevent_timestamp = Column(BigInteger)
    issueevent_type = Column(VARCHAR(5000))
    issueevent_context_string = Column(VARCHAR(5000))
    issueevent_context = Column(VARCHAR(5000))
    issueevent_payload = Column(VARCHAR(5000))
    customissue_name = Column(VARCHAR(5000))
    customissue_payload = Column(VARCHAR(5000))
    received_at = Column(BigInteger)
    batch_order_number = Column(BigInteger)


class DetailedEvent(Base):
    __tablename__ = events_detailed_table_name

    sessionid = Column(BigInteger, primary_key=True)
    adoptedssreplaceurlbased_sheet_id = Column(BigInteger)
    adoptedssreplaceurlbased_text = Column(VARCHAR(5000))
    adoptedssreplaceurlbased_base_url = Column(VARCHAR(5000))
    adoptedssreplace_sheet_id = Column(BigInteger)
    adoptedssreplace_text = Column(VARCHAR(5000))
    adoptedssinsertruleurlbased_sheet_id = Column(BigInteger)
    adoptedssinsertruleurlbased_rule = Column(VARCHAR(5000))
    adoptedssinsertruleurlbased_index = Column(BigInteger)
    adoptedssinsertruleurlbased_base_url = Column(VARCHAR(5000))
    adoptedssinsertrule_sheet_id = Column(BigInteger)
    adoptedssinsertrule_rule = Column(VARCHAR(5000))
    adoptedssinsertrule_index = Column(BigInteger)
    adoptedssdeleterule_sheet_id = Column(BigInteger)
    adoptedssdeleterule_index = Column(BigInteger)
    adoptedssaddowner_sheet_id = Column(BigInteger)
    adoptedssaddowner_id = Column(BigInteger)
    adoptedssremoveowner_sheet_id = Column(BigInteger)
    adoptedssremoveowner_id = Column(BigInteger)
    clickevent_hesitationtime = Column(BigInteger)
    clickevent_label = Column(VARCHAR(5000))
    clickevent_messageid = Column(BigInteger)
    clickevent_timestamp = Column(BigInteger)
    connectioninformation_downlink = Column(BigInteger)
    connectioninformation_type = Column(VARCHAR(5000))
    consolelog_level = Column(VARCHAR(5000))
    consolelog_value = Column(VARCHAR(5000))
    cpuissue_duration = Column(BigInteger)
    cpuissue_rate = Column(BigInteger)
    cpuissue_timestamp = Column(BigInteger)
    createdocument = Column(Boolean)
    createelementnode_id = Column(BigInteger)
    createelementnode_parentid = Column(BigInteger)
    cssdeleterule_index = Column(BigInteger)
    cssdeleterule_stylesheetid = Column(BigInteger)
    cssinsertrule_index = Column(BigInteger)
    cssinsertrule_rule = Column(VARCHAR(5000))
    cssinsertrule_stylesheetid = Column(BigInteger)
    customevent_name = Column(VARCHAR(5000))
    customevent_payload = Column(VARCHAR(5000))
    fetch_duration = Column(BigInteger)
    fetch_method = Column(VARCHAR(5000))
    fetch_request = Column(VARCHAR(5000))
    fetch_response = Column(VARCHAR(5000))
    fetch_status = Column(BigInteger)
    fetch_timestamp = Column(BigInteger)
    fetch_url = Column(VARCHAR(5000))
    graphql_operationkind = Column(VARCHAR(5000))
    graphql_operationname = Column(VARCHAR(5000))
    graphql_response = Column(VARCHAR(5000))
    graphql_variables = Column(VARCHAR(5000))
    inputevent_label = Column(VARCHAR(5000))
    inputevent_messageid = Column(BigInteger)
    inputevent_timestamp = Column(BigInteger)
    inputevent_value = Column(VARCHAR(5000))
    inputevent_valuemasked = Column(Boolean)
    inputchange_id = Column(BigInteger)
    inputchange_value = Column(VARCHAR(5000))
    inputchange_value_masked = Column(Boolean)
    inputchange_label = Column(VARCHAR(5000))
    inputchange_hesitation_time = Column(BigInteger)
    inputchange_input_duration = Column(BigInteger)
    jsexception_message = Column(VARCHAR(5000))
    jsexception_name = Column(VARCHAR(5000))
    jsexception_payload = Column(VARCHAR(5000))
    jsexception_metadata = Column(VARCHAR(5000))
    memoryissue_duration = Column(BigInteger)
    memoryissue_rate = Column(BigInteger)
    memoryissue_timestamp = Column(BigInteger)
    metadata_key = Column(VARCHAR(5000))
    metadata_value = Column(VARCHAR(5000))
    mobx_payload = Column(VARCHAR(5000))
    mobx_type = Column(VARCHAR(5000))
    mouseclick_id = Column(BigInteger)
    mouseclick_hesitationtime = Column(BigInteger)
    mouseclick_label = Column(VARCHAR(5000))
    mousemove_x = Column(BigInteger)
    mousemove_y = Column(BigInteger)
    movenode_id = Column(BigInteger)
    movenode_index = Column(BigInteger)
    movenode_parentid = Column(BigInteger)
    mousethrashing_timestamp = Column(BigInteger)
    networkrequest_type = Column(VARCHAR(5000))
    networkrequest_method = Column(VARCHAR(5000))
    networkrequest_url = Column(VARCHAR(5000))
    networkrequest_request = Column(VARCHAR(5000))
    networkrequest_response = Column(VARCHAR(5000))
    networkrequest_status = Column(BigInteger)
    networkrequest_timestamp = Column(BigInteger)
    networkrequest_duration = Column(BigInteger)
    ngrx_action = Column(VARCHAR(5000))
    ngrx_duration = Column(BigInteger)
    ngrx_state = Column(VARCHAR(5000))
    otable_key = Column(VARCHAR(5000))
    otable_value = Column(VARCHAR(5000))
    pageevent_domcontentloadedeventend = Column(BigInteger)
    pageevent_domcontentloadedeventstart = Column(BigInteger)
    pageevent_firstcontentfulpaint = Column(BigInteger)
    pageevent_firstpaint = Column(BigInteger)
    pageevent_loaded = Column(Boolean)
    pageevent_loadeventend = Column(BigInteger)
    pageevent_loadeventstart = Column(BigInteger)
    pageevent_messageid = Column(BigInteger)
    pageevent_referrer = Column(VARCHAR(5000))
    pageevent_requeststart = Column(BigInteger)
    pageevent_responseend = Column(BigInteger)
    pageevent_responsestart = Column(BigInteger)
    pageevent_speedindex = Column(BigInteger)
    pageevent_timestamp = Column(BigInteger)
    pageevent_url = Column(VARCHAR(5000))
    pageloadtiming_domcontentloadedeventend = Column(BigInteger)
    pageloadtiming_domcontentloadedeventstart = Column(BigInteger)
    pageloadtiming_firstcontentfulpaint = Column(BigInteger)
    pageloadtiming_firstpaint = Column(BigInteger)
    pageloadtiming_loadeventend = Column(BigInteger)
    pageloadtiming_loadeventstart = Column(BigInteger)
    pageloadtiming_requeststart = Column(BigInteger)
    pageloadtiming_responseend = Column(BigInteger)
    pageloadtiming_responsestart = Column(BigInteger)
    pagerendertiming_speedindex = Column(BigInteger)
    pagerendertiming_timetointeractive = Column(BigInteger)
    pagerendertiming_visuallycomplete = Column(BigInteger)
    partitionedmessage_part_no = Column(BigInteger)
    partitionedmessage_part_total = Column(BigInteger)
    performancetrack_frames = Column(BigInteger)
    performancetrack_ticks = Column(BigInteger)
    performancetrack_totaljsheapsize = Column(BigInteger)
    performancetrack_usedjsheapsize = Column(BigInteger)
    performancetrackaggr_avgcpu = Column(BigInteger)
    performancetrackaggr_avgfps = Column(BigInteger)
    performancetrackaggr_avgtotaljsheapsize = Column(BigInteger)
    performancetrackaggr_avgusedjsheapsize = Column(BigInteger)
    performancetrackaggr_maxcpu = Column(BigInteger)
    performancetrackaggr_maxfps = Column(BigInteger)
    performancetrackaggr_maxtotaljsheapsize = Column(BigInteger)
    performancetrackaggr_maxusedjsheapsize = Column(BigInteger)
    performancetrackaggr_mincpu = Column(BigInteger)
    performancetrackaggr_minfps = Column(BigInteger)
    performancetrackaggr_mintotaljsheapsize = Column(BigInteger)
    performancetrackaggr_minusedjsheapsize = Column(BigInteger)
    performancetrackaggr_timestampend = Column(BigInteger)
    performancetrackaggr_timestampstart = Column(BigInteger)
    profiler_args = Column(VARCHAR(5000))
    profiler_duration = Column(BigInteger)
    profiler_name = Column(VARCHAR(5000))
    profiler_result = Column(VARCHAR(5000))
    integrationevent_timestamp = Column(BigInteger)
    integrationevent_source = Column(VARCHAR(5000))
    integrationevent_name = Column(VARCHAR(5000))
    integrationevent_message = Column(VARCHAR(5000))
    integrationevent_payload = Column(VARCHAR(5000))
    rawerrorevent_message = Column(VARCHAR(5000))
    rawerrorevent_name = Column(VARCHAR(5000))
    rawerrorevent_payload = Column(VARCHAR(5000))
    rawerrorevent_source = Column(VARCHAR(5000))
    rawerrorevent_timestamp = Column(BigInteger)
    redux_action = Column(VARCHAR(5000))
    redux_duration = Column(BigInteger)
    redux_state = Column(VARCHAR(5000))
    removenode_id = Column(BigInteger)
    removenodeattribute_id = Column(BigInteger)
    removenodeattribute_name = Column(VARCHAR(5000))
    resourceevent_decodedbodysize = Column(BigInteger)
    resourceevent_duration = Column(BigInteger)
    resourceevent_encodedbodysize = Column(BigInteger)
    resourceevent_headersize = Column(BigInteger)
    resourceevent_messageid = Column(BigInteger)
    resourceevent_method = Column(VARCHAR(5000))
    resourceevent_status = Column(BigInteger)
    resourceevent_success = Column(Boolean)
    resourceevent_timestamp = Column(BigInteger)
    resourceevent_ttfb = Column(BigInteger)
    resourceevent_type = Column(VARCHAR(5000))
    resourceevent_url = Column(VARCHAR(5000))
    resourcetiming_timestamp = Column(BigInteger)
    resourcetiming_duration = Column(BigInteger)
    resourcetiming_ttfb = Column(BigInteger)
    resourcetiming_header_size = Column(BigInteger)
    resourcetiming_encoded_body_size = Column(BigInteger)
    resourcetiming_decoded_body_size = Column(BigInteger)
    resourcetiming_url = Column(VARCHAR(5000))
    resourcetiming_initiator = Column(VARCHAR(5000))
    resourcetiming_transferred_size = Column(BigInteger)
    resourcetiming_cached = Column(Boolean)
    selectionchange_selection_start = Column(BigInteger)
    selectionchange_selection_end = Column(BigInteger)
    selectionchange_selection = Column(VARCHAR(5000))
    sessiondisconnect = Column(Boolean)
    sessiondisconnect_timestamp = Column(BigInteger)
    sessionend_timestamp = Column(BigInteger)
    sessionend_encryption_key = Column(VARCHAR(5000))
    sessionsearch_timestamp = Column(BigInteger)
    sessionsearch_partition = Column(BigInteger)
    sessionstart_projectid = Column(BigInteger)
    sessionstart_revid = Column(VARCHAR(5000))
    sessionstart_timestamp = Column(BigInteger)
    sessionstart_trackerversion = Column(VARCHAR(5000))
    sessionstart_useragent = Column(VARCHAR(5000))
    sessionstart_userbrowser = Column(VARCHAR(5000))
    sessionstart_userbrowserversion = Column(VARCHAR(5000))
    sessionstart_usercountry = Column(VARCHAR(5000))
    sessionstart_userdevice = Column(VARCHAR(5000))
    sessionstart_userdeviceheapsize = Column(BigInteger)
    sessionstart_userdevicememorysize = Column(BigInteger)
    sessionstart_userdevicetype = Column(VARCHAR(5000))
    sessionstart_useros = Column(VARCHAR(5000))
    sessionstart_userosversion = Column(VARCHAR(5000))
    sessionstart_useruuid = Column(VARCHAR(5000))
    setcssdata_data = Column(BigInteger)
    setcssdata_id = Column(BigInteger)
    setinputchecked_checked = Column(BigInteger)
    setinputchecked_id = Column(BigInteger)
    setinputtarget_id = Column(BigInteger)
    setinputtarget_label = Column(BigInteger)
    setinputvalue_id = Column(BigInteger)
    setinputvalue_mask = Column(BigInteger)
    setinputvalue_value = Column(BigInteger)
    setnodeattribute_id = Column(BigInteger)
    setnodeattribute_name = Column(BigInteger)
    setnodeattribute_value = Column(BigInteger)
    setnodedata_data = Column(BigInteger)
    setnodedata_id = Column(BigInteger)
    setnodescroll_id = Column(BigInteger)
    setnodescroll_x = Column(BigInteger)
    setnodescroll_y = Column(BigInteger)
    setpagelocation_navigationstart = Column(BigInteger)
    setpagelocation_referrer = Column(VARCHAR(5000))
    setpagelocation_url = Column(VARCHAR(5000))
    setpagevisibility_hidden = Column(Boolean)
    setviewportscroll_x = Column(BigInteger)
    setviewportscroll_y = Column(BigInteger)
    setviewportsize_height = Column(BigInteger)
    setviewportsize_width = Column(BigInteger)
    stateaction_type = Column(VARCHAR(5000))
    stateactionevent_messageid = Column(BigInteger)
    stateactionevent_timestamp = Column(BigInteger)
    stateactionevent_type = Column(VARCHAR(5000))
    timestamp_timestamp = Column(BigInteger)
    unbindnodes_total_removed_percent = Column(BigInteger)
    useranonymousid_id = Column(VARCHAR(5000))
    userid_id = Column(VARCHAR(5000))
    vuex_mutation = Column(VARCHAR(5000))
    vuex_state = Column(VARCHAR(5000))
    loadfontface_parent_id = Column(BigInteger)
    loadfontface_family = Column(VARCHAR(5000))
    loadfontface_source = Column(VARCHAR(5000))
    loadfontface_descriptors = Column(VARCHAR(5000))
    longtasks_timestamp = Column(BigInteger)
    longtasks_duration = Column(BigInteger)
    longtasks_context = Column(BigInteger)
    longtasks_containertype = Column(BigInteger)
    longtasks_containersrc = Column(VARCHAR(5000))
    longtasks_containerid = Column(VARCHAR(5000))
    longtasks_containername = Column(BigInteger)
    setnodeattributedict_id = Column(BigInteger)
    setnodeattributedict_name_key = Column(BigInteger)
    setnodeattributedict_value_key = Column(BigInteger)
    issueevent_message_id = Column(BigInteger)
    issueevent_timestamp = Column(BigInteger)
    issueevent_type = Column(VARCHAR(5000))
    issueevent_context_string = Column(VARCHAR(5000))
    issueevent_context = Column(VARCHAR(5000))
    issueevent_payload = Column(VARCHAR(5000))
    issueevent_url = Column(VARCHAR(5000))
    technicalinfo_type = Column(VARCHAR(5000))
    technicalinfo_value = Column(VARCHAR(5000))
    zustand_mutation = Column(VARCHAR(5000))
    zustand_state = Column(VARCHAR(5000))
    customissue_name = Column(VARCHAR(5000))
    customissue_payload = Column(VARCHAR(5000))
    received_at = Column(BigInteger)
    batch_order_number = Column(BigInteger)

