CREATE TABLE IF NOT EXISTS experimental.events
(
    session_id                                     UInt64,
    project_id                                     UInt16,
    event_type Enum8('CLICK'=0, 'INPUT'=1, 'LOCATION'=2,'REQUEST'=3,'PERFORMANCE'=4,'LONGTASK'=5,'ERROR'=6,'CUSTOM'=7, 'GRAPHQL'=8, 'STATEACTION'=9),
    datetime                                       DateTime,
    label Nullable(String),
    hesitation_time Nullable(UInt32),
    name Nullable(String),
    payload Nullable(String),
    level Nullable(Enum8('info'=0, 'error'=1))              DEFAULT if(event_type == 'CUSTOM', 'info', null),
    source Nullable(Enum8('js_exception'=0, 'bugsnag'=1, 'cloudwatch'=2, 'datadog'=3, 'elasticsearch'=4, 'newrelic'=5, 'rollbar'=6, 'sentry'=7, 'stackdriver'=8, 'sumologic'=9)),
    message Nullable(String),
    error_id Nullable(String),
    duration Nullable(UInt16),
    context Nullable(Enum8('unknown'=0, 'self'=1, 'same-origin-ancestor'=2, 'same-origin-descendant'=3, 'same-origin'=4, 'cross-origin-ancestor'=5, 'cross-origin-descendant'=6, 'cross-origin-unreachable'=7, 'multiple-contexts'=8)),
    container_type Nullable(Enum8('window'=0, 'iframe'=1, 'embed'=2, 'object'=3)),
    container_id Nullable(String),
    container_name Nullable(String),
    container_src Nullable(String),
    url Nullable(String),
    url_host Nullable(String)                      MATERIALIZED lower(domain(url)),
    url_path Nullable(String)                      MATERIALIZED lower(pathFull(url)),
    url_hostpath Nullable(String)                  MATERIALIZED concat(url_host, url_path),
    request_start Nullable(UInt16),
    response_start Nullable(UInt16),
    response_end Nullable(UInt16),
    dom_content_loaded_event_start Nullable(UInt16),
    dom_content_loaded_event_end Nullable(UInt16),
    load_event_start Nullable(UInt16),
    load_event_end Nullable(UInt16),
    first_paint Nullable(UInt16),
    first_contentful_paint_time Nullable(UInt16),
    speed_index Nullable(UInt16),
    visually_complete Nullable(UInt16),
    time_to_interactive Nullable(UInt16),
    ttfb Nullable(UInt16)                          MATERIALIZED if(greaterOrEquals(response_start, request_start),
                                                                   minus(response_start, request_start), Null),
    ttlb Nullable(UInt16)                          MATERIALIZED if(greaterOrEquals(response_end, request_start),
                                                                   minus(response_end, request_start), Null),
    response_time Nullable(UInt16)                 MATERIALIZED if(greaterOrEquals(response_end, response_start),
                                                                   minus(response_end, response_start), Null),
    dom_building_time Nullable(UInt16)             MATERIALIZED if(
            greaterOrEquals(dom_content_loaded_event_start, response_end),
            minus(dom_content_loaded_event_start, response_end), Null),
    dom_content_loaded_event_time Nullable(UInt16) MATERIALIZED if(
            greaterOrEquals(dom_content_loaded_event_end, dom_content_loaded_event_start),
            minus(dom_content_loaded_event_end, dom_content_loaded_event_start), Null),
    load_event_time Nullable(UInt16)               MATERIALIZED if(greaterOrEquals(load_event_end, load_event_start),
                                                                   minus(load_event_end, load_event_start), Null),
    min_fps Nullable(UInt8),
    avg_fps Nullable(UInt8),
    max_fps Nullable(UInt8),
    min_cpu Nullable(UInt8),
    avg_cpu Nullable(UInt8),
    max_cpu Nullable(UInt8),
    min_total_js_heap_size Nullable(UInt64),
    avg_total_js_heap_size Nullable(UInt64),
    max_total_js_heap_size Nullable(UInt64),
    min_used_js_heap_size Nullable(UInt64),
    avg_used_js_heap_size Nullable(UInt64),
    max_used_js_heap_size Nullable(UInt64),
    method Nullable(Enum8('GET' = 0, 'HEAD' = 1, 'POST' = 2, 'PUT' = 3, 'DELETE' = 4, 'CONNECT' = 5, 'OPTIONS' = 6, 'TRACE' = 7, 'PATCH' = 8)),
    status Nullable(UInt16),
    success Nullable(UInt8),
    request_body Nullable(String),
    response_body Nullable(String),
    _timestamp                                     DateTime DEFAULT now()
) ENGINE = MergeTree
      PARTITION BY toYYYYMM(datetime)
      ORDER BY (project_id, datetime, event_type, session_id)
      TTL datetime + INTERVAL 3 MONTH;